# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: extension.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'extension.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65xtension.proto\x12\x06protos\"h\n\x10\x45xtensionRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\t\x12\x12\n\nindicators\x18\x02 \x03(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x04 \x01(\t\x12\r\n\x05token\x18\x05 \x01(\t\"\x13\n\x11\x45xtensionResponse2U\n\rDataExtension\x12\x44\n\rExtensionData\x12\x18.protos.ExtensionRequest\x1a\x19.protos.ExtensionResponseB\x14Z\x12systemiq.ai/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'extension_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022systemiq.ai/protos'
  _globals['_EXTENSIONREQUEST']._serialized_start=27
  _globals['_EXTENSIONREQUEST']._serialized_end=131
  _globals['_EXTENSIONRESPONSE']._serialized_start=133
  _globals['_EXTENSIONRESPONSE']._serialized_end=152
  _globals['_DATAEXTENSION']._serialized_start=154
  _globals['_DATAEXTENSION']._serialized_end=239
# @@protoc_insertion_point(module_scope)
